<?php

namespace Tests;

use App\Models\Company;
use App\Models\Employee;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication, WithFaker, RefreshDatabase;

    protected $headers = [];
    protected $user;
    protected $company;
    protected $employee;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->seed();
        Artisan::call('migrate');
        Artisan::call('passport:install');

        $this->user = User::factory()->create();
        $this->company = Company::factory()->create();
        $this->employee = Employee::factory()->create();
        $this->headers['Accept'] = 'application/json';

    }
}
